name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git email, name
        run: |
          git config --global user.email "deploy@github.com"
          git config --global user.name "hansol"

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build and Deploy ğŸ”§
        run: |
          npm i
          npm run deploy
